### ISSUE TITLE
Error when initializing year

### ISSUE THREAD

**Issue by mortenscheel** [apexatoll/aoc-cli#1]
Hi.

When I run `aoc -y 2020` to initialize the year, I get this error:
```
no implicit conversion from nil to integer
```
I'm on Mac, with Ruby from Homebrew (`ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]`)
I've tried running the command in both zsh and bash. Have tried both gem and manual install.
The session token is stored in `~/.config/aoc-cli`

**Comment by apexatoll** [comment]
Has a meta file been written in the directory you tried to initialise? If so could you post the contents here (its called .meta, should be in the directory)

**Comment by apexatoll** [comment]
This error likely means your session key is not set properly, I could reproduce this error using a bogus key I typed at random into my config file

If you go into `~/.config/aoc-cli/aoc.rc` you should see the key under the format

`cookie=>your_alias=>your_key`

The key should start with session= and there should be no spaces between anything

**Comment by mortenscheel** [comment]
Thanks. I had just add the session id without the `session=` prefix.

**Comment by apexatoll** [comment]
No problem, I will be adding some better key validation in the next version
