### ISSUE TITLE
In newest version, submission seems broken

### ISSUE THREAD

**Issue by yspreen** [apexatoll/aoc-cli#11]
```
(.pyenv) ➜  07 git:(main) ✗ aoc -s 1226
no implicit conversion of nil into String
```

I already tried reinitiating the 07 folder many times. No luck

**Comment by apexatoll** [comment]
I'm not able to reproduce this on my side. Can you send meta file and try refreshing the year directory as well

**Comment by yspreen** [comment]
I did try to refresh the year directory as well with no luck.

Day:
```
dir=>DAY
user=>main
year=>2017
day=>7
part=>1
```

Year:
```
dir=>ROOT
user=>main
year=>2017
```

**Comment by apexatoll** [comment]
I  believe this is due to a response from the server where you have tried to answer a question you have already answered - I will have to add a new error message for this. The simplest fix is to increment the part number manually and refresh the directory

**Comment by yspreen** [comment]
Interesting. I didn't think it was that, because I thought I installed v 0.2.1 and then it worked
