### ISSUE TITLE
Error when downloading part two

### ISSUE THREAD

**Issue by yspreen** [apexatoll/aoc-cli#13]
```
Correct! Downloading part two...
no implicit conversion of nil into String
```

I think I had this before, and downgraded to a pretty old version. Today I reinstalled everything, deleted all DBs and caches, and the issue is back.

**Comment by yspreen** [comment]
`.meta` remains unchanged:
```
dir=>DAY
user=>main
year=>2016
day=>10
part=>1
```

**Comment by yspreen** [comment]
Confirmed same issue as #9, it wasn't fixed

**Comment by yspreen** [comment]
I already ran `-r` after upgrading. I tried again just now, resulting in:

```
aoc -r
- Updating puzzle...
No such file or directory @ rb_sysopen - /Users/user/.cache/aoc-cli/main/2016/10/input
```

**Comment by yspreen** [comment]
The directory for 2016/10 was created with this installation of aoc-cli though. So refreshing shouldn't be needed

**Comment by apexatoll** [comment]
I've noticed similar bugs recently - I have a feeling that something must have changed server side that has broken the parser. When I have time I will get round to this, but I am super tied up at the moment - I am happy to accept a PR :)

**Comment by yspreen** [comment]
It's most definitely not server-side, since the issues popped up when updating the cli. I've never written or read ruby code but I'll give it a shot!

**Comment by apexatoll** [comment]
I believe this is just a case of updating your cookie in your config file. There are two new fields required under the heading _gid and _ga. If you find your cookie string again and copy and paste this value into your config it should work - if it does I will update the readme

**Comment by yspreen** [comment]
Seems like that's it!
