### ISSUE TITLE
implicit conversion from nil

### ISSUE THREAD

**Issue by yspreen** [apexatoll/aoc-cli#14]
**edit:** since this project is abandoned and in ruby, I decided to rewrite it in python. exact same functionality, see here: https://github.com/yspreen/aoc

---

This is happening for part two in 2016, day 18.  
I could fix the issue (day.md was not updating) by running `-r`:

```
 aoc -s 19991126
Correct! This day is now complete!
- Updating calendar...
no implicit conversion from nil to integer
(.pyenv) ➜  18 git:(main) ✗ aoc -r
- Updating puzzle...
```

**Comment by apexatoll** [comment]
Please try the latest version!
