### ISSUE TITLE
Support for 2021

### ISSUE THREAD

**Issue by guillemglez** [apexatoll/aoc-cli#15]
2021 is currently not supported: 

```
$ aoc -y 2021
Error: Invalid year: 2021
Advent of Code currently spans 2015 - 2020.
```

**Comment by apexatoll** [comment]
There will be a big update coming out in the next couple of days - keep checking back!

**Comment by guillemglez** [comment]
Great 🤩 Thank you!!!

**Comment by yspreen** [comment]
@apexatoll could we reopen this?
