### ISSUE TITLE
It's 2021!

### ISSUE THREAD

**Issue by yspreen** [apexatoll/aoc-cli#17]
**edit:** since this project is abandoned and in ruby, I decided to rewrite it in python. exact same functionality, see here: https://github.com/yspreen/aoc

---

```
> aoc -y 2021             
Error: Invalid year: 2021
Advent of Code currently spans 2015 - 2020.
```

**Comment by apexatoll** [comment]
Please try out the latest version - its a complete overhaul of the application. The date boundaries are evaluated dynamically.
