### ISSUE TITLE
Cannot submit the second part of the solution

### ISSUE THREAD

**Issue by yspreen** [apexatoll/aoc-cli#19]
**edit:** since this project is abandoned and in ruby, I decided to rewrite it in python. exact same functionality, see here: https://github.com/yspreen/aoc

---

`-s` works once, but if I do it for part 2:

```
✗ aoc -s 8295
/Library/Ruby/Gems/2.6.0/gems/aoc_cli-0.2.3/lib/aoc_cli/solve.rb:33:in `const_get': no implicit conversion of nil into String (TypeError)
        from /Library/Ruby/Gems/2.6.0/gems/aoc_cli-0.2.3/lib/aoc_cli/solve.rb:33:in `respond'
        from /Library/Ruby/Gems/2.6.0/gems/aoc_cli-0.2.3/lib/aoc_cli/commands.rb:74:in `exec'
        from /Library/Ruby/Gems/2.6.0/gems/aoc_cli-0.2.3/lib/aoc_cli/interface.rb:10:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/aoc_cli-0.2.3/lib/aoc_cli/interface.rb:6:in `initialize'
        from /Library/Ruby/Gems/2.6.0/gems/aoc_cli-0.2.3/bin/aoc:4:in `new'
        from /Library/Ruby/Gems/2.6.0/gems/aoc_cli-0.2.3/bin/aoc:4:in `<top (required)>'
        from /usr/local/bin/aoc:23:in `load'
        from /usr/local/bin/aoc:23:in `<main>'
```

**Comment by agargiulo** [comment]
I had no issues with this for part 1 or 2. Have you tried a newer version of Ruby? My computer is on `ruby 3.1.3` and as long as I edit the code to allow 2022 as a valid year, the rest just worked as intended.

**Comment by yspreen** [comment]
@agargiulo took me like 20min to update ruby, still the same error now

**Comment by agargiulo** [comment]
Huh that's really weird. I was personally running into issues with 2022 before the year properly released that seemed to have similar errors but that was "nil cannot be converted to an int" or such. I might have time to dig more into this later, but this repo has all but been abandoned based on last commit date and a few other things so I'm not sure if that will pan out.

**Comment by yspreen** [comment]
@agargiulo I noticed that my new session ID cookie was much longer than the old one. seems like they did make changes to the architecture over at AOC

**Comment by apexatoll** [comment]
Please try out the latest version - its a complete overhaul of the application
