### ISSUE TITLE
Initializing a year tells me "no such file or directory - pandoc"

### ISSUE THREAD

**Issue by agargiulo** [apexatoll/aoc-cli#2]
```
[10:14:06] % bundle exec aoc -y 2020
No such file or directory - pandoc
```

Meta file was created as such:
```
[10:14:31] % less .meta
dir=>ROOT
user=>agargiulo
year=>2020
```

Running ruby 2.7.2 on macOS Big Sur 11.2.1
To install, I added `gem 'aoc_cli'` to my Gemfile and ran `bundle install`

**Comment by apexatoll** [comment]
Pandoc is one of aoc-cli's dependencies, if you use homebrew you can install it with `brew install pandoc`. Otherwise install here https://pandoc.org/installing.html

**Comment by agargiulo** [comment]
I see, so that's separate from the gem `pandoc-ruby`?

**Comment by apexatoll** [comment]
Yes, pandoc-ruby is just a wrapper for pandoc in Ruby :)

**Comment by agargiulo** [comment]
Okay thanks. That fixed my issue :D
