### ISSUE TITLE
Better handling of the session= error

### ISSUE THREAD

**Issue by yspreen** [apexatoll/aoc-cli#5]
I had the same issue as #1 

The problem is, once you set the session wrong, doing it with the right format results in 

```
> aoc -k 'session=53616c...'
wrong number of arguments (given 0, expected 1)
```

I think the aoc -k command should check for the right format. The error message showcased in #1 should also be more informative

**Comment by apexatoll** [comment]
Thanks for the feedback - there is an update coming in the next couple of days with some more features, one of which being better key validation
