### ISSUE TITLE
Custom Naming for Day Directory

### ISSUE THREAD

**Issue by cjpappas** [apexatoll/aoc-cli#7]
Would it be possible to set a custom naming format for the day directory that is created with the `aoc -d` command. This would be useful in Java projects where sub-directories (that are treated as packages) can't start with a number (usually just prefixed with an underscore).

**Comment by yspreen** [comment]
I think you can just make your own folder and put the .meta file in there?

```
dir=>DAY
user=>main
year=>2018
day=>22
part=>1
```

For 2018 day 22.

**Comment by apexatoll** [comment]
This has now been implemented in 0.2.1 (please update). You can set a prefix for day subdirectories in your config file using `day_dir_prefix=>prefix`

For example `day_dir_prefix=>day` would mean your day subdirs would be of the format day_10 etc
