### ISSUE TITLE
Submitting solution causes error, part two isn't downloaded

### ISSUE THREAD

**Issue by yspreen** [apexatoll/aoc-cli#9]
This seems to be introduced in 0.2? I'm running 0.2.2.

```
(.pyenv) ➜  24 git:(main) ✗ aoc -s 15493
Correct! Downloading part two...
no implicit conversion of nil into String
# (24.md hasn't changed)
```

**Comment by apexatoll** [comment]
can you post your meta file?
You may need to update the part manually to '2' if you have not reinitialised once upgrading. Try to aoc -r as well

**Comment by yspreen** [comment]
```
dir=>DAY
user=>main
year=>2018
day=>24
part=>1
```

**Comment by yspreen** [comment]
But how exactly can I avoid this in the future?

**Comment by apexatoll** [comment]
You need to change part=>1 to part=>2

My guess is that this was in a directory initialised under a previous version of aoc

**Comment by yspreen** [comment]
I mean yeah, it probably was. But what causes the bug? Is there a table
missing somewhere, which causes the part number to not update?

**Comment by apexatoll** [comment]
I cannot say for sure - I recommend that you refresh each of your existing aoc directories using 'aoc -r'. This should create any missing databases
